### ISSUE TITLE
Concepts already implemented in Nim at time of publishing

### ISSUE THREAD

**Issue by ZoomRmc** [Verdagon/VerdagonSite#17]
https://github.com/Verdagon/VerdagonSite/blob/da63cb0b9ad3b92949a4d21191b8343c7b358f87/src/blog/0.2/concept-functions.vmd#L53

Not sure when exactly, but they had been implemented for a few years by 2022 when the article was published.
The current state: https://nim-lang.org/docs/manual_experimental.html#concepts
The redesign (testing implementation exists): https://github.com/nim-lang/RFCs/issues/168

```nim
type
  Strong = concept t
    t.strength is int

  Damaging = concept a, b
    calcDamage(a, b) is int

func calcDamage(attacker, target: Strong): int =
  attacker.strength - target.strength

func battle(attacker, defender: Damaging): int =
  calcDamage(attacker, defender)

type Ship = object
  strength: int

let rocinante = Ship(strength: 10)
let  bessie = Ship(strength: 9000)

echo bessie.battle(rocinante)
```

**Comment by Verdagon** [comment]
Added a mention for Nim's concepts, thanks for the heads up!
